### ISSUE TITLE
CSS dashboard - lack of arrows for asc and desc sort

### ISSUE THREAD

**Issue by apricotpoodle** [FriendsOfCake/bootstrap-ui#280]
This is a : CSS enhancement
* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 1.4.1..
* Bootstrap Framework Version: 3.3.7
* jQuery: LIBRARY VERSION
* Platform and Target:  who cares in this case ? :P

### What you did
For adding this functionnality 
I added this code in **MY OWN**
vendor/friendsofcake/bootstrap-ui/webroot/css/dashboard.css.

```css
/*
 * Global add-ons
 */
/* added default values found in style.css
.asc:after {content: " \2193";}
.desc:after {content: " \2191";}
*/
/* these ones are more funkies */
.asc:after { content: " \e155"; }
.desc:after { content: " \e156";}

```

This code solves the lack of BootStrapUI css and now display gently small icons beside sorted columns header

### Expected Behavior
by default sorted column headers should be displayed with an icon beside.
The classes "asc" and "desc" should be displayed if necessary

### Actual Behavior
sorted column headers are not automagically gently displayed 
with a small icon (arrow, whatever, …)
Even if in the html code a class "asc" or "desc" is generated, 
these class are not considered by BootstrapUI css file.

Before you open an issue, please check if a similar issue already exists or has been closed before.

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/cakephp)
for that or join the #cakephp channel on irc.freenode.net, where we will be more
than happy to help answer your questions.
