### ISSUE TITLE
Different width for textbox and  textarea

### ISSUE THREAD

**Issue by Monsur-Hoq** [FriendsOfCake/bootstrap-ui#98]
When we set **align** property in form create, by default textbox and textarea width depends on that property value. Is it possible to set different width for different textbox and textarea for same form?

**Comment by ayman-alkom** [comment]
I think that this issue is my related to the Bootstrap CSS itself, you can simply treat it with a custom css of yours like this:
```CSS
.form-group.textarea .col-md-6 {
    width: 100%;
    padding-top: 10px;
}
```
this worked for me
